### ISSUE TITLE
Support for mocking nested CAConfig

### ISSUE THREAD

**Issue by roszpapad** [wcm-io/io.wcm.testing.wcm-io-mock.caconfig#1]
Hi,

In a project, we use nested CAConfigs. It is working correctly, but we are having a hard time creating mock content for it. `MockContextAwareConfig.writeConfiguration` works fine with non-nested configs, but doesn’t seem to be helpful in nested cases.
Please let me know if I missed any currently existing solution. If I didn't then can you please check how to make it possible to support nested cases?

Background:
Why did we use nested CAConfigs? Since we don't have multifield in CAConfigs we added a CAConfig typed array field to another CAConfig.

**Comment by stefanseifert** [comment]
it is possible to express nested configurations, but it's very ugly and partially bypassing the actual API design of MockContextAwareConfig - it definitely makes sense to find a better solution. it's not there already as it's a bit difficult to find a clean an concise way to express this nested configuration data in unit test code.

the actual code base which needs to be extended is https://github.com/apache/sling-org-apache-sling-testing-caconfig-mock-plugin, though.

i plan to look for a better solution in the next weeks (PRs here or to https://github.com/apache/sling-org-apache-sling-testing-caconfig-mock-plugin are welcome, of course)

**Comment by roszpapad** [comment]
Hi @stefanseifert ,
Thank you for your answer. I am not sure if I will have time in the near future to dig deep into the code :/ 

Also, this topic has a very low priority for us, so please take your time. Any update on this topic will be appreciated. Thank you in advance!

**Comment by stefanseifert** [comment]
i've created https://issues.apache.org/jira/browse/SLING-11839 and a PR https://github.com/apache/sling-org-apache-sling-testing-caconfig-mock-plugin/pull/3 to solve the issue.

basically the signature of the `writeConfiguration` and `writeConfigurationCollection` methods are unchanged, but if the map data passed to theses methods contain nested maps or nested lists of maps, they are stored as nested configurations. that should make it easy to prepare nested caconfig in unit tests.

can you give it a try if ti works for you?

**Comment by stefanseifert** [comment]
https://github.com/apache/sling-org-apache-sling-testing-caconfig-mock-plugin/pull/3 is merged, to be releases as part of caconfig-mock-plugin 1.5.0

**Comment by roszpapad** [comment]
Sorry for the late answer. Thank you so much for this feature. As 1.5.0 will be released we will definitely use it.

**Comment by stefanseifert** [comment]
caconfig-mock-plugin 1.5.0 released to maven central
